# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: fraud_api
    metrics_path: /metrics
    static_configs:
      - targets:
          - api:8000

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

rule_files:
  - "rules.yml"