global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: fraud_api
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
