name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: fraud_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements_api.txt
          pip install -r requirements_dev.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .

      - name: Run tests
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/fraud_db
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest --cov=.

      - name: Build API Docker image
        run: docker compose build api
