name: Nightly Fraud Summary Backup

# Runs at 02:00 UTC every day

on:
schedule:
\- cron: '0 2 \* \* \*'

jobs:
backup:
runs-on: ubuntu-latest
steps:
\- name: Check out repo
uses: actions/checkout\@v3

```
  - name: Set up Docker Compose
    uses: docker/setup-buildx-action@v2
    with:
      buildkitd-flags: --debug

  - name: Start Postgres container
    run: |
      docker-compose up -d postgres

  - name: Wait for Postgres to be ready
    run: |
      until docker exec fraud-postgres pg_isready -U postgres; do
        echo "Waiting for Postgres..." && sleep 2
      done

  - name: Run backup script
    run: |
      chmod +x backup_fraud_summary.sh
      ./backup_fraud_summary.sh

  - name: Upload backup as artifact
    uses: actions/upload-artifact@v3
    with:
      name: fraud-summary-backup-${{ github.run_date }}
      path: backups/fraud_summary_*.csv
```
